---
kind: pipeline
name: Codequality
steps:
- commands:
  - php -v
  - composer update
  image: joomlaprojects/docker-images:php8.1
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpcs --standard=ruleset.xml src/
  depends:
  - composer
  image: joomlaprojects/docker-images:php8.1
  name: phpcs
- commands:
  - vendor/bin/phan
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1-ast
  name: phan
- commands:
  - ./vendor/bin/phpstan
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phpstan
- commands:
  - phploc src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phploc
- commands:
  - phpcpd src
  depends:
  - composer
  failure: ignore
  image: joomlaprojects/docker-images:php8.1
  name: phpcpd
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.1 lowest
steps:
- commands:
  - php -v
  - composer update --prefer-stable --prefer-lowest
  image: joomlaprojects/docker-images:php8.1
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php8.1
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.1
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php8.1
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php8.1
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.2
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php8.2
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php8.2
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.3
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php8.3
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  failure: ignore
  image: joomlaprojects/docker-images:php8.3
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: pipeline
name: PHP 8.4
steps:
- commands:
  - php -v
  - composer update --prefer-stable
  image: joomlaprojects/docker-images:php8.4
  name: composer
  volumes:
  - name: composer-cache
    path: /tmp/composer-cache
- commands:
  - vendor/bin/phpunit
  image: joomlaprojects/docker-images:php8.4
  name: PHPUnit
volumes:
- host:
    path: /tmp/composer-cache
  name: composer-cache
---
kind: signature
hmac: d2d6a6466ef93f89a335bc056242f3054760b9096514d6ccec6cc2aaac83abba

...
